// CLI Commands - Auto-generated from main.js
const CLI_COMMANDS = [
    {
      id: "daily",
      category: "daily",
      name: "打开日记",
      desc: "打开今日每日笔记",
      params: [
        {
          name: "paneType",
          label: "打开方式",
          type: "select",
          options: ["tab", "split", "window"],
          required: true,
        },
      ],
    },
    {
      id: "daily:path",
      category: "daily",
      name: "获取日记路径",
      desc: "获取今日日记文件路径",
      params: [],
    },
    {
      id: "daily:read",
      category: "daily",
      name: "读取日记",
      desc: "读取今日日记内容",
      params: [],
    },
    {
      id: "daily:append",
      category: "daily",
      name: "追加到日记",
      desc: "向今日日记末尾追加内容",
      params: [
        {
          name: "content",
          label: "内容",
          type: "textarea",
          required: false,
          placeholder: "输入要追加的内容...",
        },
        {
          name: "paneType",
          label: "打开方式",
          type: "select",
          options: ["tab", "split", "window"],
          required: true,
        },
        { name: "inline", label: "不换行追加", type: "flag", required: true },
        { name: "open", label: "执行后打开", type: "flag", required: true },
      ],
    },
    {
      id: "daily:prepend",
      category: "daily",
      name: "插入到日记开头",
      desc: "向今日日记开头插入内容",
      params: [
        {
          name: "content",
          label: "内容",
          type: "textarea",
          required: false,
          placeholder: "输入要插入的内容...",
        },
        {
          name: "paneType",
          label: "打开方式",
          type: "select",
          options: ["tab", "split", "window"],
          required: true,
        },
        { name: "inline", label: "不换行插入", type: "flag", required: true },
        { name: "open", label: "执行后打开", type: "flag", required: true },
      ],
    },
    {
      id: "file",
      category: "files",
      name: "文件信息",
      desc: "显示文件详细信息",
      params: [
        {
          name: "file",
          label: "文件名",
          type: "text",
          required: true,
          placeholder: "留空=当前文件",
        },
        {
          name: "path",
          label: "文件路径",
          type: "text",
          required: true,
          placeholder: "folder/note.md",
        },
      ],
    },
    {
      id: "files",
      category: "files",
      name: "列出文件",
      desc: "列出仓库中的文件",
      params: [
        { name: "folder", label: "文件夹", type: "text", required: true },
        {
          name: "ext",
          label: "扩展名",
          type: "text",
          required: true,
          placeholder: "md",
        },
        { name: "total", label: "仅显示数量", type: "flag", required: true },
      ],
    },
    {
      id: "open",
      category: "files",
      name: "打开文件",
      desc: "打开指定文件",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "newtab", label: "新标签页", type: "flag", required: true },
      ],
    },
    {
      id: "create",
      category: "files",
      name: "创建文件",
      desc: "创建新文件",
      params: [
        {
          name: "name",
          label: "文件名",
          type: "text",
          required: true,
          placeholder: "留空则为 Untitled",
        },
        {
          name: "path",
          label: "完整路径",
          type: "text",
          required: true,
          placeholder: "文件夹/文件名.md",
        },
        {
          name: "content",
          label: "内容",
          type: "textarea",
          required: true,
          placeholder: "支持换行（Enter 键），将自动转为 \\n",
        },
        {
          name: "template",
          label: "模板路径",
          type: "text",
          required: true,
          placeholder: '需要开启"模板"核心插件',
        },
        { name: "overwrite", label: "覆盖已有", type: "flag", required: true },
        { name: "open", label: "创建后打开", type: "flag", required: true },
        { name: "newtab", label: "新标签页", type: "flag", required: true },
      ],
    },
    {
      id: "read",
      category: "files",
      name: "读取文件",
      desc: "读取文件内容",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "append",
      category: "files",
      name: "追加内容",
      desc: "向文件末尾追加",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "content", label: "内容", type: "textarea", required: false },
        { name: "inline", label: "不换行", type: "flag", required: true },
      ],
    },
    {
      id: "prepend",
      category: "files",
      name: "插入到开头",
      desc: "在frontmatter后插入",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "content", label: "内容", type: "textarea", required: false },
        { name: "inline", label: "不换行", type: "flag", required: true },
      ],
    },
    {
      id: "move",
      category: "files",
      name: "移动文件",
      desc: "移动或重命名文件",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "to", label: "目标路径", type: "text", required: false },
      ],
    },
    {
      id: "rename",
      category: "files",
      name: "重命名",
      desc: "重命名文件",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "name", label: "新名称", type: "text", required: false },
      ],
    },
    {
      id: "delete",
      category: "files",
      name: "删除文件",
      desc: "删除文件（默认回收站）",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "permanent", label: "永久删除", type: "flag", required: true },
      ],
      dangerous: false,
    },
    {
      id: "folder",
      category: "files",
      name: "文件夹信息",
      desc: "显示文件夹信息",
      params: [
        { name: "path", label: "路径", type: "text", required: false },
        {
          name: "info",
          label: "类型",
          type: "select",
          options: ["files", "folders", "size"],
          required: true,
        },
      ],
    },
    {
      id: "folders",
      category: "files",
      name: "列出文件夹",
      desc: "列出仓库文件夹",
      params: [
        { name: "folder", label: "父文件夹", type: "text", required: true },
        { name: "total", label: "仅数量", type: "flag", required: true },
      ],
    },
    {
      id: "wordcount",
      category: "files",
      name: "字数统计",
      desc: "统计字数和字符数",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "words", label: "仅字数", type: "flag", required: true },
        { name: "characters", label: "仅字符数", type: "flag", required: true },
      ],
    },
    {
      id: "search",
      category: "search",
      name: "搜索",
      desc: "全库文本搜索",
      params: [
        {
          name: "query",
          label: "关键词",
          type: "text",
          required: false,
          placeholder: "搜索关键词",
        },
        { name: "path", label: "限定文件夹", type: "text", required: true },
        { name: "limit", label: "最大数", type: "number", required: true },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["text", "json"],
          required: true,
        },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "case", label: "区分大小写", type: "flag", required: true },
      ],
    },
    {
      id: "search:context",
      category: "search",
      name: "搜索（含上下文）",
      desc: "搜索并显示匹配行",
      params: [
        { name: "query", label: "关键词", type: "text", required: false },
        { name: "path", label: "限定文件夹", type: "text", required: true },
        { name: "limit", label: "最大数", type: "number", required: true },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["text", "json"],
          required: true,
        },
        { name: "case", label: "区分大小写", type: "flag", required: true },
      ],
    },
    {
      id: "search:open",
      category: "search",
      name: "打开搜索面板",
      desc: "打开搜索视图",
      params: [{ name: "query", label: "关键词", type: "text", required: true }],
    },
    {
      id: "tasks",
      category: "tasks",
      name: "列出任务",
      desc: "列出仓库中的任务",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "status", label: "状态字符", type: "text", required: true },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["text", "json", "tsv", "csv"],
          required: true,
        },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "done", label: "已完成", type: "flag", required: true },
        { name: "todo", label: "未完成", type: "flag", required: true },
        { name: "verbose", label: "详细", type: "flag", required: true },
        { name: "active", label: "当前文件", type: "flag", required: true },
        { name: "daily", label: "今日日记", type: "flag", required: true },
      ],
    },
    {
      id: "task",
      category: "tasks",
      name: "操作任务",
      desc: "查看或更新任务",
      params: [
        {
          name: "ref",
          label: "引用",
          type: "text",
          required: true,
          placeholder: "path:line",
        },
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "line", label: "行号", type: "number", required: true },
        { name: "status", label: "状态", type: "text", required: true },
        { name: "toggle", label: "切换", type: "flag", required: true },
        { name: "done", label: "完成", type: "flag", required: true },
        { name: "todo", label: "待办", type: "flag", required: true },
        { name: "daily", label: "日记", type: "flag", required: true },
      ],
    },
    {
      id: "backlinks",
      category: "links",
      name: "反向链接",
      desc: "列出反向链接",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "counts", label: "数量", type: "flag", required: true },
        { name: "total", label: "仅总数", type: "flag", required: true },
      ],
    },
    {
      id: "links",
      category: "links",
      name: "出站链接",
      desc: "列出出站链接",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "total", label: "仅总数", type: "flag", required: true },
      ],
    },
    {
      id: "unresolved",
      category: "links",
      name: "未解析链接",
      desc: "列出断链",
      params: [
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "total", label: "仅总数", type: "flag", required: true },
        { name: "counts", label: "数量", type: "flag", required: true },
        { name: "verbose", label: "源文件", type: "flag", required: true },
      ],
    },
    {
      id: "orphans",
      category: "links",
      name: "孤立笔记（整库）",
      desc: "整库中没有被引用的文件",
      params: [{ name: "total", label: "仅总数", type: "flag", required: true }],
    },
    {
      id: "orphans:folder",
      category: "links",
      name: "孤立笔记（按文件夹）",
      desc: "指定文件夹内既无入链也无出链的文件（虚拟命令）",
      isVirtual: false,
      params: [
        {
          name: "folder",
          label: "文件夹路径",
          type: "text",
          required: false,
          placeholder: "例如 Projects 或 Notes/Archive",
        },
        {
          name: "ext",
          label: "扩展名过滤",
          type: "text",
          required: true,
          placeholder: "留空=仅md，all=全部，或指定如jpg,png",
        },
        { name: "total", label: "仅数量", type: "flag", required: true },
      ],
    },
    {
      id: "deadends",
      category: "links",
      name: "死胡同笔记",
      desc: "没有出站链接的文件",
      params: [{ name: "total", label: "仅总数", type: "flag", required: true }],
    },
    {
      id: "tags",
      category: "tags",
      name: "列出标签",
      desc: "列出仓库标签",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        {
          name: "sort",
          label: "排序",
          type: "select",
          options: ["name", "count"],
          required: true,
        },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "total", label: "仅总数", type: "flag", required: true },
        { name: "counts", label: "数量", type: "flag", required: true },
        { name: "active", label: "当前文件", type: "flag", required: true },
      ],
    },
    {
      id: "tag",
      category: "tags",
      name: "标签信息",
      desc: "查看标签详情",
      params: [
        { name: "name", label: "标签名", type: "text", required: false },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "verbose", label: "文件列表", type: "flag", required: true },
      ],
    },
    {
      id: "properties",
      category: "properties",
      name: "列出属性",
      desc: "列出仓库属性",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "name", label: "属性名", type: "text", required: true },
        {
          name: "sort",
          label: "排序",
          type: "select",
          options: ["name", "count"],
          required: true,
        },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["yaml", "json", "tsv"],
          required: true,
        },
        { name: "total", label: "仅总数", type: "flag", required: true },
        { name: "counts", label: "数量", type: "flag", required: true },
        { name: "active", label: "当前文件", type: "flag", required: true },
      ],
    },
    {
      id: "property:set",
      category: "properties",
      name: "设置属性",
      desc: "设置文件属性",
      params: [
        { name: "name", label: "属性名", type: "text", required: false },
        { name: "value", label: "属性值", type: "text", required: false },
        {
          name: "type",
          label: "类型",
          type: "select",
          options: ["text", "list", "number", "checkbox", "date", "datetime"],
          required: true,
        },
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "property:remove",
      category: "properties",
      name: "删除属性",
      desc: "删除文件属性",
      params: [
        { name: "name", label: "属性名", type: "text", required: false },
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "property:read",
      category: "properties",
      name: "读取属性",
      desc: "读取属性值",
      params: [
        { name: "name", label: "属性名", type: "text", required: false },
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "templates",
      category: "templates",
      name: "列出模板",
      desc: "列出所有模板",
      params: [{ name: "total", label: "仅数量", type: "flag", required: true }],
    },
    {
      id: "template:read",
      category: "templates",
      name: "读取模板",
      desc: "读取模板内容",
      params: [
        { name: "name", label: "模板名", type: "text", required: false },
        { name: "title", label: "标题变量", type: "text", required: true },
        { name: "resolve", label: "解析变量", type: "flag", required: true },
      ],
    },
    {
      id: "template:insert",
      category: "templates",
      name: "插入模板",
      desc: "插入模板到当前文件",
      params: [
        {
          name: "name",
          label: "模板名",
          type: "text",
          required: false,
          placeholder: '需要开启"模板"核心插件',
        },
      ],
    },
    {
      id: "bookmarks",
      category: "bookmarks",
      name: "列出书签",
      desc: "列出所有书签",
      params: [
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "verbose", label: "类型", type: "flag", required: true },
      ],
    },
    {
      id: "bookmark",
      category: "bookmarks",
      name: "添加书签",
      desc: "添加新书签",
      params: [
        { name: "file", label: "文件", type: "text", required: true },
        { name: "subpath", label: "子路径", type: "text", required: true },
        { name: "folder", label: "文件夹", type: "text", required: true },
        { name: "search", label: "搜索", type: "text", required: true },
        { name: "url", label: "URL", type: "text", required: true },
        { name: "title", label: "标题", type: "text", required: true },
      ],
    },
    {
      id: "plugins",
      category: "plugins",
      name: "列出插件",
      desc: "列出已安装插件",
      params: [
        {
          name: "filter",
          label: "类型",
          type: "select",
          options: ["core", "community"],
          required: true,
        },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "versions", label: "版本", type: "flag", required: true },
      ],
    },
    {
      id: "plugins:enabled",
      category: "plugins",
      name: "已启用插件",
      desc: "列出已启用插件",
      params: [
        {
          name: "filter",
          label: "类型",
          type: "select",
          options: ["core", "community"],
          required: true,
        },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "versions", label: "版本", type: "flag", required: true },
      ],
    },
    {
      id: "plugin",
      category: "plugins",
      name: "插件信息",
      desc: "查看插件详情",
      params: [{ name: "id", label: "插件ID", type: "text", required: false }],
    },
    {
      id: "plugin:enable",
      category: "plugins",
      name: "启用插件",
      desc: "启用插件",
      params: [
        { name: "id", label: "插件ID", type: "text", required: false },
        {
          name: "filter",
          label: "类型",
          type: "select",
          options: ["core", "community"],
          required: true,
        },
      ],
    },
    {
      id: "plugin:disable",
      category: "plugins",
      name: "禁用插件",
      desc: "禁用插件",
      params: [
        { name: "id", label: "插件ID", type: "text", required: false },
        {
          name: "filter",
          label: "类型",
          type: "select",
          options: ["core", "community"],
          required: true,
        },
      ],
    },
    {
      id: "plugin:install",
      category: "plugins",
      name: "安装插件",
      desc: "安装社区插件",
      params: [
        { name: "id", label: "插件ID", type: "text", required: false },
        { name: "enable", label: "安装后启用", type: "flag", required: true },
      ],
    },
    {
      id: "plugin:uninstall",
      category: "plugins",
      name: "卸载插件",
      desc: "卸载插件",
      params: [{ name: "id", label: "插件ID", type: "text", required: false }],
      dangerous: false,
    },
    {
      id: "plugin:reload",
      category: "plugins",
      name: "重载插件",
      desc: "重载插件（开发用）",
      params: [{ name: "id", label: "插件ID", type: "text", required: false }],
    },
    {
      id: "themes",
      category: "themes",
      name: "列出主题",
      desc: "列出已安装主题",
      params: [{ name: "versions", label: "版本", type: "flag", required: true }],
    },
    {
      id: "theme",
      category: "themes",
      name: "当前主题",
      desc: "查看当前主题",
      params: [{ name: "name", label: "主题名", type: "text", required: true }],
    },
    {
      id: "theme:set",
      category: "themes",
      name: "设置主题",
      desc: "切换主题",
      params: [{ name: "name", label: "主题名", type: "text", required: false }],
    },
    {
      id: "theme:install",
      category: "themes",
      name: "安装主题",
      desc: "安装社区主题",
      params: [
        { name: "name", label: "主题名", type: "text", required: false },
        { name: "enable", label: "安装后启用", type: "flag", required: true },
      ],
    },
    {
      id: "theme:uninstall",
      category: "themes",
      name: "卸载主题",
      desc: "卸载主题",
      params: [{ name: "name", label: "主题名", type: "text", required: false }],
      dangerous: false,
    },
    {
      id: "snippets",
      category: "themes",
      name: "CSS片段",
      desc: "列出CSS片段",
      params: [],
    },
    {
      id: "snippets:enabled",
      category: "themes",
      name: "已启用CSS",
      desc: "已启用CSS片段",
      params: [],
    },
    {
      id: "snippet:enable",
      category: "themes",
      name: "启用CSS",
      desc: "启用CSS片段",
      params: [{ name: "name", label: "片段名", type: "text", required: false }],
    },
    {
      id: "snippet:disable",
      category: "themes",
      name: "禁用CSS",
      desc: "禁用CSS片段",
      params: [{ name: "name", label: "片段名", type: "text", required: false }],
    },
    {
      id: "vault",
      category: "vault",
      name: "仓库信息",
      desc: "当前仓库信息",
      params: [
        {
          name: "info",
          label: "类型",
          type: "select",
          options: ["name", "path", "files", "folders", "size"],
          required: true,
        },
      ],
    },
    {
      id: "vaults",
      category: "vault",
      name: "列出仓库",
      desc: "所有已知仓库",
      params: [
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "verbose", label: "路径", type: "flag", required: true },
      ],
    },
    {
      id: "workspace",
      category: "workspace",
      name: "工作区树",
      desc: "当前工作区布局",
      params: [{ name: "ids", label: "显示ID", type: "flag", required: true }],
    },
    {
      id: "workspaces",
      category: "workspace",
      name: "列出工作区",
      desc: "已保存工作区",
      params: [{ name: "total", label: "仅数量", type: "flag", required: true }],
    },
    {
      id: "workspace:save",
      category: "workspace",
      name: "保存工作区",
      desc: "保存当前布局",
      params: [{ name: "name", label: "名称", type: "text", required: true }],
    },
    {
      id: "workspace:load",
      category: "workspace",
      name: "加载工作区",
      desc: "加载工作区",
      params: [{ name: "name", label: "名称", type: "text", required: false }],
    },
    {
      id: "workspace:delete",
      category: "workspace",
      name: "删除工作区",
      desc: "删除工作区",
      params: [{ name: "name", label: "名称", type: "text", required: false }],
      dangerous: false,
    },
    {
      id: "tabs",
      category: "workspace",
      name: "标签页",
      desc: "列出打开的标签页",
      params: [],
    },
    {
      id: "tab:open",
      category: "workspace",
      name: "打开标签页",
      desc: "打开新标签页",
      params: [
        { name: "group", label: "标签组", type: "text", required: true },
        { name: "file", label: "文件", type: "text", required: true },
        { name: "view", label: "视图", type: "text", required: true },
      ],
    },
    {
      id: "recents",
      category: "workspace",
      name: "最近文件",
      desc: "最近打开的文件",
      params: [{ name: "total", label: "仅数量", type: "flag", required: true }],
    },
    {
      id: "publish:site",
      category: "publish",
      name: "站点信息",
      desc: "发布站点信息",
      params: [],
    },
    {
      id: "publish:list",
      category: "publish",
      name: "已发布文件",
      desc: "已发布的文件",
      params: [{ name: "total", label: "仅数量", type: "flag", required: true }],
    },
    {
      id: "publish:status",
      category: "publish",
      name: "发布状态",
      desc: "发布变更",
      params: [
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "new", label: "新文件", type: "flag", required: true },
        { name: "changed", label: "已修改", type: "flag", required: true },
        { name: "deleted", label: "已删除", type: "flag", required: true },
      ],
    },
    {
      id: "publish:add",
      category: "publish",
      name: "发布文件",
      desc: "发布文件",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "changed", label: "所有变更", type: "flag", required: true },
      ],
    },
    {
      id: "publish:remove",
      category: "publish",
      name: "取消发布",
      desc: "取消发布",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "publish:open",
      category: "publish",
      name: "在线预览",
      desc: "在发布站点打开",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "sync",
      category: "sync",
      name: "同步开关",
      desc: "暂停/恢复同步",
      params: [
        { name: "on", label: "恢复", type: "flag", required: true },
        { name: "off", label: "暂停", type: "flag", required: true },
      ],
    },
    {
      id: "sync:status",
      category: "sync",
      name: "同步状态",
      desc: "同步状态和用量",
      params: [],
    },
    {
      id: "sync:history",
      category: "sync",
      name: "同步历史",
      desc: "同步版本历史",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "total", label: "仅数量", type: "flag", required: true },
      ],
    },
    {
      id: "sync:read",
      category: "sync",
      name: "读取同步版本",
      desc: "读取同步版本",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "version", label: "版本号", type: "number", required: false },
      ],
    },
    {
      id: "sync:restore",
      category: "sync",
      name: "恢复同步版本",
      desc: "恢复同步版本",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "version", label: "版本号", type: "number", required: false },
      ],
      dangerous: false,
    },
    {
      id: "sync:open",
      category: "sync",
      name: "打开同步历史",
      desc: "打开同步历史",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "sync:deleted",
      category: "sync",
      name: "已删除文件",
      desc: "同步中已删除文件",
      params: [{ name: "total", label: "仅数量", type: "flag", required: true }],
    },
    {
      id: "diff",
      category: "history",
      name: "版本对比",
      desc: "对比历史版本",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "from", label: "起始版本", type: "number", required: true },
        { name: "to", label: "目标版本", type: "number", required: true },
        {
          name: "filter",
          label: "来源",
          type: "select",
          options: ["local", "sync"],
          required: true,
        },
      ],
    },
    {
      id: "history",
      category: "history",
      name: "文件历史",
      desc: "历史版本列表",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "history:list",
      category: "history",
      name: "有历史的文件",
      desc: "有本地历史的文件",
      params: [],
    },
    {
      id: "history:read",
      category: "history",
      name: "读取历史",
      desc: "读取历史版本",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "version", label: "版本号", type: "number", required: true },
      ],
    },
    {
      id: "history:restore",
      category: "history",
      name: "恢复历史",
      desc: "恢复历史版本",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "version", label: "版本号", type: "number", required: false },
      ],
      dangerous: false,
    },
    {
      id: "history:open",
      category: "history",
      name: "文件恢复",
      desc: "打开文件恢复",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
      ],
    },
    {
      id: "devtools",
      category: "dev",
      name: "开发者工具",
      desc: "切换开发者工具",
      params: [],
    },
    {
      id: "dev:debug",
      category: "dev",
      name: "调试器",
      desc: "连接/断开调试器",
      params: [
        { name: "on", label: "连接", type: "flag", required: true },
        { name: "off", label: "断开", type: "flag", required: true },
      ],
    },
    {
      id: "dev:cdp",
      category: "dev",
      name: "CDP命令",
      desc: "执行CDP命令",
      params: [
        { name: "method", label: "方法", type: "text", required: false },
        { name: "params", label: "参数JSON", type: "textarea", required: true },
      ],
    },
    {
      id: "dev:errors",
      category: "dev",
      name: "错误日志",
      desc: "查看JS错误",
      params: [{ name: "clear", label: "清除", type: "flag", required: true }],
    },
    {
      id: "dev:screenshot",
      category: "dev",
      name: "截图",
      desc: "截取应用截图",
      params: [{ name: "path", label: "保存路径", type: "text", required: true }],
    },
    {
      id: "dev:console",
      category: "dev",
      name: "控制台",
      desc: "查看控制台消息",
      params: [
        { name: "limit", label: "最大数", type: "number", required: true },
        {
          name: "level",
          label: "级别",
          type: "select",
          options: ["log", "warn", "error", "info", "debug"],
          required: true,
        },
        { name: "clear", label: "清除", type: "flag", required: true },
      ],
    },
    {
      id: "dev:css",
      category: "dev",
      name: "CSS检查",
      desc: "检查CSS样式",
      params: [
        { name: "selector", label: "选择器", type: "text", required: false },
        { name: "prop", label: "属性", type: "text", required: true },
      ],
    },
    {
      id: "dev:dom",
      category: "dev",
      name: "DOM查询",
      desc: "查询DOM元素",
      params: [
        { name: "selector", label: "选择器", type: "text", required: false },
        { name: "attr", label: "属性", type: "text", required: true },
        { name: "css", label: "CSS属性", type: "text", required: true },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "text", label: "文本", type: "flag", required: true },
        { name: "inner", label: "innerHTML", type: "flag", required: true },
        { name: "all", label: "所有", type: "flag", required: true },
      ],
    },
    {
      id: "dev:mobile",
      category: "dev",
      name: "移动端模拟",
      desc: "切换移动端",
      params: [
        { name: "on", label: "启用", type: "flag", required: true },
        { name: "off", label: "禁用", type: "flag", required: true },
      ],
    },
    {
      id: "eval",
      category: "dev",
      name: "执行JS",
      desc: "执行JavaScript",
      params: [
        {
          name: "code",
          label: "JS代码",
          type: "textarea",
          required: false,
          placeholder: "app.vault.getFiles().length",
        },
      ],
    },
    {
      id: "help",
      category: "other",
      name: "帮助",
      desc: "显示帮助",
      params: [],
    },
    {
      id: "version",
      category: "other",
      name: "版本",
      desc: "Obsidian版本",
      params: [],
    },
    {
      id: "reload",
      category: "other",
      name: "重新加载",
      desc: "重新加载窗口",
      params: [],
    },
    {
      id: "restart",
      category: "other",
      name: "重启",
      desc: "重启Obsidian",
      params: [],
    },
    {
      id: "random",
      category: "other",
      name: "随机笔记",
      desc: "打开随机笔记",
      params: [
        { name: "folder", label: "文件夹", type: "text", required: true },
        { name: "newtab", label: "新标签页", type: "flag", required: true },
      ],
    },
    {
      id: "random:read",
      category: "other",
      name: "读取随机笔记",
      desc: "读取随机笔记",
      params: [{ name: "folder", label: "文件夹", type: "text", required: true }],
    },
    {
      id: "web",
      category: "other",
      name: "打开网页",
      desc: "内置浏览器打开URL",
      params: [
        {
          name: "url",
          label: "URL",
          type: "text",
          required: false,
          placeholder: "https://...",
        },
        { name: "newtab", label: "新标签页", type: "flag", required: true },
      ],
    },
    {
      id: "outline",
      category: "other",
      name: "大纲",
      desc: "文件标题大纲",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tree", "md", "json"],
          required: true,
        },
        { name: "total", label: "仅数量", type: "flag", required: true },
      ],
    },
    {
      id: "aliases",
      category: "other",
      name: "别名",
      desc: "列出别名",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "文件路径", type: "text", required: true },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "verbose", label: "文件路径", type: "flag", required: true },
        { name: "active", label: "当前文件", type: "flag", required: true },
      ],
    },
    {
      id: "commands",
      category: "other",
      name: "命令列表",
      desc: "可用命令ID",
      params: [{ name: "filter", label: "前缀", type: "text", required: true }],
    },
    {
      id: "command",
      category: "other",
      name: "执行命令",
      desc: "执行Obsidian命令",
      params: [{ name: "id", label: "命令ID", type: "text", required: false }],
    },
    {
      id: "hotkeys",
      category: "other",
      name: "快捷键",
      desc: "列出快捷键",
      params: [
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["tsv", "json", "csv"],
          required: true,
        },
        { name: "total", label: "仅数量", type: "flag", required: true },
        { name: "verbose", label: "自定义", type: "flag", required: true },
      ],
    },
    {
      id: "hotkey",
      category: "other",
      name: "查看快捷键",
      desc: "命令的快捷键",
      params: [
        { name: "id", label: "命令ID", type: "text", required: false },
        { name: "verbose", label: "自定义", type: "flag", required: true },
      ],
    },
    {
      id: "bases",
      category: "base",
      name: "Bases",
      desc: "列出.base文件",
      params: [],
    },
    {
      id: "base:views",
      category: "base",
      name: "Base视图",
      desc: "Base的视图",
      params: [],
    },
    {
      id: "base:create",
      category: "base",
      name: "创建Base条目",
      desc: "在base数据库某个视图中创建新条目文档（注意不是创建base文档）。如果未指定文件，则默认使用当前活动数据库视图。",
      params: [
        { name: "file", label: "base文件名", type: "text", required: true },
        { name: "path", label: "路径", type: "text", required: true },
        { name: "view", label: "视图名", type: "text", required: true },
        { name: "name", label: "新条目文件名", type: "text", required: true },
        {
          name: "content",
          label: "条目文档内容",
          type: "textarea",
          required: true,
        },
        { name: "open", label: "打开", type: "flag", required: true },
        { name: "newtab", label: "新标签页", type: "flag", required: true },
      ],
    },
    {
      id: "base:query",
      category: "base",
      name: "查询Base",
      desc: "查询Base",
      params: [
        { name: "file", label: "文件名", type: "text", required: true },
        { name: "path", label: "路径", type: "text", required: true },
        { name: "view", label: "视图", type: "text", required: true },
        {
          name: "format",
          label: "格式",
          type: "select",
          options: ["json", "csv", "tsv", "md", "paths"],
          required: true,
        },
      ],
    },
    {
      id: "unique",
      category: "other",
      name: "唯一笔记",
      desc: "创建唯一笔记",
      params: [
        { name: "name", label: "名称", type: "text", required: true },
        { name: "content", label: "内容", type: "textarea", required: true },
        {
          name: "paneType",
          label: "打开方式",
          type: "select",
          options: ["tab", "split", "window"],
          required: true,
        },
        { name: "open", label: "打开", type: "flag", required: true },
      ],
    },
    {
      id: "agent",
      category: "agent",
      name: "Agent",
      desc: "调用 FlowText Agent 执行智能任务（需安装 FlowText 插件）",
      isVirtual: false,
      params: [
        {
          name: "content",
          label: "任务描述",
          type: "textarea",
          required: false,
          placeholder: "描述需要 Agent 执行的任务...",
        },
        {
          name: "path",
          label: "目标文件",
          type: "text",
          required: true,
          placeholder: "文件路径",
        },
      ],
    },
module.exports = { CLI_COMMANDS };
