import type { CLICommanderSettings } from "../../types";

export const DEFAULT_SETTINGS: CLICommanderSettings = {
  userPresets: [],
  userPresetGroups: [],
  presetGroupCollapsed: {},
  workflowGroups: [],
  wfGroupCollapsed: {},
  manualWorkflows: [],
  workflowSources: [],
  executionHistory: [],
  maxHistory: 50,
  showCommandPreview: true,
  confirmDangerous: true,
  favorites: [],
  hiddenBuiltinPresets: [],
  builtinPresetOrder: [],
  homePresetIds: null,
  evalLastCode: "",
  evalSnippets: [],
  evalSnippetGroups: [],
  evalSnippetGroupCollapsed: {},
  moveConflictRename: true,
  moveConflictSuffix: "number",
  showResultPanel: true,
};
